# Generated by Django 4.2.3 on 2023-07-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobProposalBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
