# Generated by Django 4.2.3 on 2023-07-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('time_connected', models.FloatField()),
                ('last_login', models.DateTimeField()),
                ('button_1_counter', models.IntegerField()),
                ('button_2_counter', models.IntegerField()),
            ],
        ),
    ]
